### ISSUE TITLE
ESP32 + KSZ8863 Daughter Board I2C Problem (IDFGH-10896)

### ISSUE THREAD

**Issue by AM0219350** [espressif/esp-eth-drivers#16]
Hello,
I'm using this KSZ8863 ethernet driver to build my project. My hardware was assembled with ESP32 and AC320004-7(KSZ8863 Daughter Board). Now I can use SPI interface successfully and get the IP address from DHCP router. But i can't do the same thing with I2C interface. Here are what i have done and other information below. Thanks.

According to the document of AC320004-7. I wonder to use I2C interface.
1. R34 & R35 Replace with 4.7k
2. R28 & R29 [ Placed,DNP ] chose I2C Slave Mode
3. Revising the I2C speed with 100 khz. Because the 100 kHz it seems better than 400 kHz on SCL signal.
4. Revising the IDF menuconfig to set output of reference clock by ESP32 pin 17. 

IDF message:
![image](https://github.com/espressif/esp-eth-drivers/assets/12125404/294dd839-484d-474e-95fb-0466db0eb291)

I2C signal:
![image](https://github.com/espressif/esp-eth-drivers/assets/12125404/537b4463-1235-47f4-801c-648e11016222)

Reference:
1. AC320004-7 - KSZ8863 ETHERNET PHY DAUGHTER BOARD
  -https://www.microchip.com/en-us/development-tool/ac320004-7

Regards,
Ken.

**Comment by kostaond** [comment]
It seems like sending command error, slave hasn't ACK the transfer.

> Revising the IDF menuconfig to set output of reference clock by ESP32 pin 17.

Is this the same configuration you used when KSZ8863 was in SPI communication mode?

**Comment by AM0219350** [comment]
Hi Kostaond,
Thanks for your reply. I set the same configuration both SPI and I2C. They accept the input reference clock from ESP32 pin 17. 
Earlier time. I used the oscilloscope to check the signal. I found that my SCL amplitudes are very short. Sorry I didn't save that screenshot. But I draw it below. I used the simple_switch example. Just change the clock reference and conmunication mode. I think the signals are not similar to open-drain gpio.  Does the ESP32 needs to be specially set to open-drain when setting the I2C pin?

![image](https://github.com/espressif/esp-eth-drivers/assets/12125404/3da4e053-fbdc-433b-a5c3-d87ae1d63e6e)

Warm regards,
Ken.

**Comment by AM0219350** [comment]
Hi Kostaond,
I did some test for I2C siginal. And the other information for you. See the screenshots. Thanks.

1. Menuconfig
![image](https://github.com/espressif/esp-eth-drivers/assets/12125404/a8bef60f-0386-4976-a1f8-802a9c5613fc)
2. I2C open-drain circuit
![4  ESP32_open-drain接線](https://github.com/espressif/esp-eth-drivers/assets/12125404/b852c329-f76c-4add-9352-390c3ed063ef)
3. I2C speed 400khz
![6  ESP32_I2C-speed-400khz](https://github.com/espressif/esp-eth-drivers/assets/12125404/a9d8527c-d1ef-49be-b3ba-32999928d7c4)
4. I2C speed 100khz
![7  ESP32_I2C-speed-100khz](https://github.com/espressif/esp-eth-drivers/assets/12125404/fe7996d2-8cb1-4eda-a469-ec2723e6faff)
5. ESP Version
![1  ESP32_WROOM-32D](https://github.com/espressif/esp-eth-drivers/assets/12125404/c9ab43f4-c421-4b62-ae0d-e6615cf72007)

Regeards,
Ken.

**Comment by kostaond** [comment]
> I used the oscilloscope to check the signal. I found that my SCL amplitudes are very short.

Do you have probe attenuation properly configured for channel 2? It looks like 1/3 of 1V div, which is 0.33V which is 10 times less than expected.

**Comment by AM0219350** [comment]
Hi Kostaond,
Sorry my it's fault. My oscilloscope probe is out of order. So that the I2C signal is correct. But I can't get response from KSZ8863(I2C slave mode). There are new information below. Is there any other way to check that the setting of KSZ8863 is correct? Thanks.

1. I2C signal from oscilloscope.
![P_20230822_112041](https://github.com/espressif/esp-eth-drivers/assets/12125404/6da88f2a-f7d8-42e0-9cfb-79515e07807b)

2. I2C signal from logic analyzer
![image](https://github.com/espressif/esp-eth-drivers/assets/12125404/b9581ef1-ec7e-4869-bbb8-3825898b303e)

3. Using ESP32 I2C tool to detect I2C addresses.
![image](https://github.com/espressif/esp-eth-drivers/assets/12125404/669b03da-7134-42b9-80f6-db19a8489e34)

4. Screenshot 3 captured by logic analyzer
![image](https://github.com/espressif/esp-eth-drivers/assets/12125404/1814cf41-b5be-4a9a-b06c-4034bdb19421)

Regards.
Ken.

**Comment by kostaond** [comment]
Using ESP32 I2C tool to detect I2C addresses is smart move. However, did you make sure that RMII REF CLK (50 MHz) was generated? If not, the KSZ8863 would be "dead".

It's really strange if it worked with SPI. I spent quite time thinking about the issue and I have no idea what could be wrong...

I would suggest the following:
1) Double check that changes required to switch the KSZ8863 to I2C client mode were properly done. For example, resistors were soldered reliably and no other components were affected. These are small parts and it may just happen desoldering one part, the neighbor component may fall due to heat...
2) Make sure that RMII CLK is present at REFCLKI_3 and X1.
3) Double check that SCL_MDC is connected to ESP32 GPIO 23 and SDA_MDIO is connected to ESP32 GPIO 18.

Regards,
Ondrej

**Comment by AM0219350** [comment]
Hi Kostaond,
OK. I will check the I2C setting and contact the microchip for help. I will attach you the SPI interface status. There is a unknown io command. But the switch procedures still working successfully. Thank you.

1. ESP32 serial data
![image](https://github.com/espressif/esp-eth-drivers/assets/12125404/d910eaf2-4c95-46d4-a0b1-786f78a8028d)

2. The possible position of the unknown IO command in the program.
![image](https://github.com/espressif/esp-eth-drivers/assets/12125404/98c24ae5-0969-4362-a75f-54cc28dedc8c)

3. Ping Test to 192.168.0.48
![image](https://github.com/espressif/esp-eth-drivers/assets/12125404/91cbcadd-bab9-47a9-897a-dfeb2e8a40d9)

4. Hardware connection status. 
![P_20230822_162825](https://github.com/espressif/esp-eth-drivers/assets/12125404/b1e5bc0c-78af-4a96-91b4-c1a4239a88d8)
![image](https://github.com/espressif/esp-eth-drivers/assets/12125404/3ba96dfb-dcf0-473a-87c7-40bec0cd0be6)

Regards,
Ken.

**Comment by kostaond** [comment]
SPI looks good, therefore it is strange the I2C does not work. We have test board and use it in this mode without any issues.

Regarding `unknown io command`, this is really caused by 
```c
ret = esp_eth_ioctl(eth_handle, KSZ8863_ETH_CMD_G_PORT_NUM, &port_num);
```
Three Ethernet handles are registered, one of them is internal EMAC which is a "gateway" to the KSZ8863. The internal EMAC does not know `KSZ8863_ETH_CMD_G_PORT_NUM` option which is KSZ8863 specific. So the solution is either to make `unknown io command` error silent in the ESP-IDF or to add extra infrastructure to be able to distinguish whether Ethernet handle processed by even handler is KSZ8863 related or not. Feel free to create a new GH issue to address it.

**Comment by AM0219350** [comment]
Hi Ondrej,
Finally it worked on I2C. I don't know why it works. According to the document of KSZ8863 module. It needs pull-up resistor on I2C pins for 4.7k. But in my situation. It only works with pull-up resistor 1k. At least I can continue my program job first. Next I will wait for our PCB to be made. Thank you again for your assistance.
Warm regards,
Ken.

1. KSZ8863 Daughter Board Information Sheet. page 5
![image](https://github.com/espressif/esp-eth-drivers/assets/12125404/0ed10511-044b-44d2-92b7-5b68a7798741)

**Comment by kostaond** [comment]
@AM0219350, great to hear you were able to found the issue! Probably the impedance of longer wires could cause it? 

Could you please close the issue?

**Comment by AM0219350** [comment]
Hi Ondrej,
In my experience. The modules that I used for I2C interface. They all use longer lines than this. The document suggested that I use a 4.7K resistor is also a reason. Keep me from trying other values. Thanks again for your assistance.
Regards,
Ken.
